<div class="field clubhouse_profile<?= $block->isRequired() ? ' required' : ''; ?>">
    <label class="label" for="clubhouse_profile">
        <span><?php echo __('Clubhouse Profile');?></span>
    </label>
    <div class="control">
        <input type="text" name="clubhouse_profile" id="clubhouse_profile" value=""
               title="<?php echo __('Custom Attribute'); ?>" class="input-text" <?= $block->isRequired() ? ' data-validate="{required:true}"' : '' ?>>
    </div>
</div>
